volumes:
    mysql-data80:
    esdata:
    esdata79:
    esdata811:
    code:
    home:
    cert:
    phpstorm-config:

services:
    nginx.loc:
        build:
            context: nginx
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        container_name: m2-nginx
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - cert:/etc/ssl/cert
        #command: ls -la /etc/ssl/cert/
        depends_on: 
            - mailhog.loc
        ports:
            - "80:80"
            - "443:443"
# php 7.4 start
    php-fpm7.4.loc:
        build:
            context: php-fpm7.4
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
        container_name: php-fpm7.4
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
    
    php-fpm7.4-xdebug.loc:
        build:
            context: php-fpm7.4-xdebug
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php-fpm7.4-xdebug
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}

    php-env7.4.loc:
        build:
            context: php7.4-env
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php7.4-env
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
# php 7.4 end
# php 8.1 start
    php-fpm8.1.loc:
        build:
            context: php-fpm8.1
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
        container_name: php-fpm8.1
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
    
    php-fpm8.1-xdebug.loc:
        build:
            context: php-fpm8.1-xdebug
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php-fpm8.1-xdebug
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}

    php-env8.1.loc:
        build:
            context: php8.1-env
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php8.1-env
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
# php 8.1 end
# php 8.2 start
    php-fpm8.2.loc:
        build:
            context: php-fpm8.2
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
        container_name: php-fpm8.2
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
    
    php-fpm8.2-xdebug.loc:
        build:
            context: php-fpm8.2-xdebug
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php-fpm8.2-xdebug
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}

    php-env8.2.loc:
        build:
            context: php8.2-env
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php8.2-env
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
# php 8.2 end
# php 8.3 start
    php-fpm8.3.loc:
        build:
            context: php-fpm8.3
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
        container_name: php-fpm8.3
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
    
    php-fpm8.3-xdebug.loc:
        build:
            context: php-fpm8.3-xdebug
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php-fpm8.3-xdebug
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}

    php-env8.3.loc:
        build:
            context: php8.3-env
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php8.3-env
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
# php 8.3 end
# php 8.4 start
    php-fpm8.4.loc:
        build:
            context: php-fpm8.4
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
        container_name: php-fpm8.4
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
    
    php-fpm8.4-xdebug.loc:
        build:
            context: php-fpm8.4-xdebug
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php-fpm8.4-xdebug
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}

    php-env8.4.loc:
        build:
            context: php8.4-env
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: php8.4-env
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
# php 8.4 end
    node.loc:
        build:
            context: node
            dockerfile: Dockerfile
            args:
                - GUEST_CODE_PATH=${GUEST_CODE_PATH}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - HOST_IP=${HOST_IP}
                - DEBUG_IP=${DEBUG_IP}
        container_name: node
        volumes:
            - ${HOST_CODE_PATH}:${GUEST_CODE_PATH}
            - ${HOME_PATH}:/home/www-data
    mysql80.loc:
        build:
            context: mysql8.0
            dockerfile: Dockerfile
        container_name: m2-mysql80
        command: 
            - --default-authentication-plugin=mysql_native_password
            - --sort_buffer_size=1G
            - --innodb-buffer-pool-size=1G
        volumes:
            - mysql-data80:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123123q
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
            #MYSQL_DATABASE: magento
        ports:
            - "127.0.0.1:3306:3306"

    redis.loc:
        build:
            context: redis 
            dockerfile: Dockerfile
        container_name: m2-redis

    mailhog.loc:
        build:
            context: mailhog
            dockerfile: Dockerfile
        container_name: m2-mailhog

    elasticsearch811.loc:
        build:
            context: elasticsearch8.11
            dockerfile: Dockerfile
        container_name: m2-elasticsearch811
        environment:
            - cluster.name="docker-cluster"
            - network.host=0.0.0.0
            - action.auto_create_index=true
            - discovery.seed_hosts=elasticsearch79.loc
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        volumes:
            - esdata811:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    rabbitmq39.loc:
        build:
            context: rabbitmq
            dockerfile: Dockerfile
        container_name: m2-rabbitmq39
        environment:
            RABBITMQ_DEFAULT_USER: "magento"
            RABBITMQ_DEFAULT_PASS: "magento"

    
